apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: djfekh9z2-go
  janus-idp.io/tekton: djfekh9z2-go
  backstage.io/kubernetes-id: djfekh9z2-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: djfekh9z2-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
