apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: djfekh9z2-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: djfekh9z2-go 
  name: djfekh9z2-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: djfekh9z2-go 
